# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gen_data = QtWidgets.QGroupBox(self.centralwidget)
        self.Gen_data.setGeometry(QtCore.QRect(10, 10, 171, 121))
        self.Gen_data.setObjectName("Gen_data")
        self.layoutWidget = QtWidgets.QWidget(self.Gen_data)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 92))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btn_train_size = QtWidgets.QLineEdit(self.layoutWidget)
        self.btn_train_size.setObjectName("btn_train_size")
        self.gridLayout_3.addWidget(self.btn_train_size, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.btn_test_size = QtWidgets.QLineEdit(self.layoutWidget)
        self.btn_test_size.setObjectName("btn_test_size")
        self.gridLayout_3.addWidget(self.btn_test_size, 1, 1, 1, 1)
        self.btn_gen = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_gen.setObjectName("btn_gen")
        self.gridLayout_3.addWidget(self.btn_gen, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.G_image_option = QtWidgets.QGroupBox(self.centralwidget)
        self.G_image_option.setGeometry(QtCore.QRect(20, 130, 161, 301))
        self.G_image_option.setObjectName("G_image_option")
        self.lbl_img_size = QtWidgets.QLabel(self.G_image_option)
        self.lbl_img_size.setGeometry(QtCore.QRect(10, 30, 71, 16))
        self.lbl_img_size.setObjectName("lbl_img_size")
        self.Ibl_objects = QtWidgets.QLabel(self.G_image_option)
        self.Ibl_objects.setGeometry(QtCore.QRect(10, 110, 101, 24))
        self.Ibl_objects.setObjectName("Ibl_objects")
        self.layoutWidget2 = QtWidgets.QWidget(self.G_image_option)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 50, 141, 57))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.in_img_size_H = QtWidgets.QLineEdit(self.layoutWidget2)
        self.in_img_size_H.setObjectName("in_img_size_H")
        self.gridLayout.addWidget(self.in_img_size_H, 0, 1, 1, 1)
        self.in_img_size_W = QtWidgets.QLineEdit(self.layoutWidget2)
        self.in_img_size_W.setObjectName("in_img_size_W")
        self.gridLayout.addWidget(self.in_img_size_W, 1, 1, 1, 1)
        self.Ibl_img_size_W = QtWidgets.QLabel(self.layoutWidget2)
        self.Ibl_img_size_W.setObjectName("Ibl_img_size_W")
        self.gridLayout.addWidget(self.Ibl_img_size_W, 1, 0, 1, 1)
        self.Ibl_img_size_H = QtWidgets.QLabel(self.layoutWidget2)
        self.Ibl_img_size_H.setObjectName("Ibl_img_size_H")
        self.gridLayout.addWidget(self.Ibl_img_size_H, 0, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.G_image_option)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 140, 146, 138))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Ibl_objs_num = QtWidgets.QLabel(self.layoutWidget3)
        self.Ibl_objs_num.setObjectName("Ibl_objs_num")
        self.gridLayout_2.addWidget(self.Ibl_objs_num, 0, 0, 1, 1)
        self.in_num_objs = QtWidgets.QLineEdit(self.layoutWidget3)
        self.in_num_objs.setObjectName("in_num_objs")
        self.gridLayout_2.addWidget(self.in_num_objs, 0, 1, 1, 2)
        self.chk_box_circle = QtWidgets.QCheckBox(self.layoutWidget3)
        self.chk_box_circle.setChecked(True)
        self.chk_box_circle.setObjectName("chk_box_circle")
        self.gridLayout_2.addWidget(self.chk_box_circle, 1, 0, 1, 2)
        self.chk_box_squre = QtWidgets.QCheckBox(self.layoutWidget3)
        self.chk_box_squre.setObjectName("chk_box_squre")
        self.gridLayout_2.addWidget(self.chk_box_squre, 2, 0, 1, 2)
        self.chk_box_triangle = QtWidgets.QCheckBox(self.layoutWidget3)
        self.chk_box_triangle.setObjectName("chk_box_triangle")
        self.gridLayout_2.addWidget(self.chk_box_triangle, 3, 0, 1, 2)
        self.lbl_objs_fill = QtWidgets.QLabel(self.layoutWidget3)
        self.lbl_objs_fill.setObjectName("lbl_objs_fill")
        self.gridLayout_2.addWidget(self.lbl_objs_fill, 4, 0, 1, 1)
        self.in_objs_fill = QtWidgets.QLineEdit(self.layoutWidget3)
        self.in_objs_fill.setObjectName("in_objs_fill")
        self.gridLayout_2.addWidget(self.in_objs_fill, 4, 2, 1, 1)
        self.btn_train = QtWidgets.QPushButton(self.centralwidget)
        self.btn_train.setGeometry(QtCore.QRect(220, 30, 93, 28))
        self.btn_train.setObjectName("btn_train")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gen_data.setTitle(_translate("MainWindow", "Generate Data"))
        self.btn_train_size.setText(_translate("MainWindow", "1000"))
        self.label.setText(_translate("MainWindow", "Train Data"))
        self.btn_test_size.setText(_translate("MainWindow", "100"))
        self.btn_gen.setText(_translate("MainWindow", "Generate"))
        self.label_2.setText(_translate("MainWindow", "Test_data"))
        self.G_image_option.setTitle(_translate("MainWindow", "Image Option"))
        self.lbl_img_size.setText(_translate("MainWindow", "Image size"))
        self.Ibl_objects.setText(_translate("MainWindow", "Objects"))
        self.in_img_size_H.setText(_translate("MainWindow", "200"))
        self.in_img_size_W.setText(_translate("MainWindow", "200"))
        self.Ibl_img_size_W.setText(_translate("MainWindow", "Width"))
        self.Ibl_img_size_H.setText(_translate("MainWindow", "Height"))
        self.Ibl_objs_num.setText(_translate("MainWindow", "How many"))
        self.in_num_objs.setText(_translate("MainWindow", "2"))
        self.chk_box_circle.setText(_translate("MainWindow", "Circle"))
        self.chk_box_squre.setText(_translate("MainWindow", "Squre"))
        self.chk_box_triangle.setText(_translate("MainWindow", "Triangle"))
        self.lbl_objs_fill.setText(_translate("MainWindow", "Fill"))
        self.in_objs_fill.setText(_translate("MainWindow", "1"))
        self.btn_train.setText(_translate("MainWindow", "Train a net"))

