# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 846)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Gen_data = QtWidgets.QGroupBox(self.centralwidget)
        self.Gen_data.setGeometry(QtCore.QRect(10, 320, 211, 126))
        self.Gen_data.setObjectName("Gen_data")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.Gen_data)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.Gen_data)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.btn_train_size = QtWidgets.QLineEdit(self.Gen_data)
        self.btn_train_size.setObjectName("btn_train_size")
        self.verticalLayout_3.addWidget(self.btn_train_size)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.Gen_data)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_8.addWidget(self.label_2)
        self.btn_test_size = QtWidgets.QLineEdit(self.Gen_data)
        self.btn_test_size.setObjectName("btn_test_size")
        self.verticalLayout_8.addWidget(self.btn_test_size)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.btn_gendataset = QtWidgets.QPushButton(self.Gen_data)
        self.btn_gendataset.setObjectName("btn_gendataset")
        self.verticalLayout_9.addWidget(self.btn_gendataset)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_Logger = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_Logger.setGeometry(QtCore.QRect(10, 590, 781, 201))
        self.text_Logger.setObjectName("text_Logger")
        self.G_image_option_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.G_image_option_2.setGeometry(QtCore.QRect(10, 20, 211, 296))
        self.G_image_option_2.setObjectName("G_image_option_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.G_image_option_2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Ibl_img_size_H = QtWidgets.QLabel(self.G_image_option_2)
        self.Ibl_img_size_H.setObjectName("Ibl_img_size_H")
        self.horizontalLayout_3.addWidget(self.Ibl_img_size_H)
        self.in_img_size_H = QtWidgets.QLineEdit(self.G_image_option_2)
        self.in_img_size_H.setObjectName("in_img_size_H")
        self.horizontalLayout_3.addWidget(self.in_img_size_H)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Ibl_img_size_W = QtWidgets.QLabel(self.G_image_option_2)
        self.Ibl_img_size_W.setObjectName("Ibl_img_size_W")
        self.horizontalLayout_4.addWidget(self.Ibl_img_size_W)
        self.in_img_size_W = QtWidgets.QLineEdit(self.G_image_option_2)
        self.in_img_size_W.setObjectName("in_img_size_W")
        self.horizontalLayout_4.addWidget(self.in_img_size_W)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.G_image_option = QtWidgets.QGroupBox(self.G_image_option_2)
        self.G_image_option.setObjectName("G_image_option")
        self.gridLayout = QtWidgets.QGridLayout(self.G_image_option)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chk_box_circle = QtWidgets.QCheckBox(self.G_image_option)
        self.chk_box_circle.setChecked(True)
        self.chk_box_circle.setObjectName("chk_box_circle")
        self.verticalLayout_4.addWidget(self.chk_box_circle)
        self.chk_box_squre = QtWidgets.QCheckBox(self.G_image_option)
        self.chk_box_squre.setObjectName("chk_box_squre")
        self.verticalLayout_4.addWidget(self.chk_box_squre)
        self.chk_box_triangle = QtWidgets.QCheckBox(self.G_image_option)
        self.chk_box_triangle.setObjectName("chk_box_triangle")
        self.verticalLayout_4.addWidget(self.chk_box_triangle)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_objs_fill = QtWidgets.QLabel(self.G_image_option)
        self.lbl_objs_fill.setObjectName("lbl_objs_fill")
        self.horizontalLayout.addWidget(self.lbl_objs_fill)
        self.in_objs_fill = QtWidgets.QLineEdit(self.G_image_option)
        self.in_objs_fill.setObjectName("in_objs_fill")
        self.horizontalLayout.addWidget(self.in_objs_fill)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Ibl_objs_num = QtWidgets.QLabel(self.G_image_option)
        self.Ibl_objs_num.setObjectName("Ibl_objs_num")
        self.verticalLayout_2.addWidget(self.Ibl_objs_num)
        self.in_num_objs = QtWidgets.QLineEdit(self.G_image_option)
        self.in_num_objs.setObjectName("in_num_objs")
        self.verticalLayout_2.addWidget(self.in_num_objs)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.G_image_option)
        self.chbox_show_configuration = QtWidgets.QCheckBox(self.G_image_option_2)
        self.chbox_show_configuration.setObjectName("chbox_show_configuration")
        self.verticalLayout_7.addWidget(self.chbox_show_configuration)
        self.btn_gen = QtWidgets.QPushButton(self.G_image_option_2)
        self.btn_gen.setObjectName("btn_gen")
        self.verticalLayout_7.addWidget(self.btn_gen)
        self.btn_train = QtWidgets.QPushButton(self.centralwidget)
        self.btn_train.setGeometry(QtCore.QRect(280, 40, 93, 28))
        self.btn_train.setObjectName("btn_train")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Gen_data.setTitle(_translate("MainWindow", "Generate Data Set"))
        self.label.setText(_translate("MainWindow", "Train Data"))
        self.btn_train_size.setText(_translate("MainWindow", "200"))
        self.label_2.setText(_translate("MainWindow", "Test_data"))
        self.btn_test_size.setText(_translate("MainWindow", "100"))
        self.btn_gendataset.setText(_translate("MainWindow", "Generate"))
        self.G_image_option_2.setTitle(_translate("MainWindow", "Objects in the image"))
        self.Ibl_img_size_H.setText(_translate("MainWindow", "Height"))
        self.in_img_size_H.setText(_translate("MainWindow", "200"))
        self.Ibl_img_size_W.setText(_translate("MainWindow", "Width"))
        self.in_img_size_W.setText(_translate("MainWindow", "200"))
        self.G_image_option.setTitle(_translate("MainWindow", "Objects in the image"))
        self.chk_box_circle.setText(_translate("MainWindow", "Circle"))
        self.chk_box_squre.setText(_translate("MainWindow", "Squre"))
        self.chk_box_triangle.setText(_translate("MainWindow", "Triangle"))
        self.lbl_objs_fill.setText(_translate("MainWindow", "Fill"))
        self.in_objs_fill.setText(_translate("MainWindow", "1"))
        self.Ibl_objs_num.setText(_translate("MainWindow", "How many ?"))
        self.in_num_objs.setText(_translate("MainWindow", "2"))
        self.chbox_show_configuration.setText(_translate("MainWindow", "Show Configuration"))
        self.btn_gen.setText(_translate("MainWindow", "Show image"))
        self.btn_train.setText(_translate("MainWindow", "Train"))

